# Site settings
title: MUSIC LESSONS
email: wearejmusicstudio@gmail.com
url: https://wearejmusicstudio.com
description: "Private and group lessons for Piano, Drum, Flute, Violin, Guitar, Clarinet and Saxophone"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: J Music Studio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:

# Build settings
markdown: kramdown
permalink: pretty
