# Site settings
title: J MUSIC STUDIO
email: wearejmusicstudio@gmail.com
url: https://wearejmusicstudio.com
description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in bibendum augue. Vivamus velit eros, suscipit ac aliquam vel, mattis convallis elit. Etiam id pellentesque dui. Cras quis elementum magna, non eleifend lectus. Phasellus vestibulum massa nec orci lacinia egestas ut ac nunc. Nulla ut ipsum facilisis, convallis erat eu, lacinia tortor. Suspendisse vel sem ut erat posuere laoreet porta a eros. Nullam ultricies tortor sed hendrerit commodo. Praesent porta justo sit amet sem euismod, quis suscipit sapien imperdiet. Donec fringilla eros fermentum felis placerat rhoncus. Nulla facilisi. Morbi tristique sapien mauris, id posuere metus eleifend nec. Proin eleifend congue nulla at dictum. Sed condimentum tincidunt metus, ut blandit augue tincidunt eu. Etiam a lorem sit amet orci imperdiet finibus."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: J Music Studio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:

# Build settings
markdown: kramdown
permalink: pretty
